### PR TITLE
Revert "HTTPClient for OWM data"

### PR DESCRIPTION
**Pull request by G6EJD**
Reverts G6EJD/ESP32-e-Paper-Weather-Display#46

Not compiling too many errors

### CODE REVIEW

**Comment by televator** [comment]
Can you please provide an error log? I am wondering why this might fail. It works for me just fine. And the CI job is happy as well.

**Comment by G6EJD** [comment]
The novice user does not approach the code in the way that you or I might.

**Comment by televator** [comment]
Do I understand correctly that not the HTTPClient is problematic, but there is a more general problem?

**Comment by G6EJD** [comment]
Yes a more general problem of libraries not found, each file needs a path so it’s found but a relative path does not work e.g. /src/epaper_fonts.h

**Pull request merged**
