### PR TITLE
Cleanup readme

### PR DESCRIPTION
**Pull request by televator**
Minor cleanup of the README.md

### CODE REVIEW

**Comment by televator** [comment]
I must confess I first need to read into the GxEPD2. But looks nice at a first glance, so I might give it a try when I find some more time.

**Comment by televator** [comment]
Are you happy with the two PRs, or how do we want to proceed?

**Comment by G6EJD** [comment]
I've now updated the 7.5" version to GxEPD, already I can see a huge improvement in display contrast from minigrafx, so ideally they all need updating to match.
I've done a lot of improvement work to the v10 and ensures US formats displays correctly, it was not displaying the date of update, but fixed that now, and improved the graphing of Imperial data.
Needs epaper_fonts.h in the sketch folder plus lang.h as usual. the old font file is not needed. epepaer_fonts also has 7-segments, but I have not used them yet.

This merge request has conflicts, which need to be resolved.

**Comment by televator** [comment]
fixed

**Pull request merged**
