### PR TITLE
HTTPClient for OWM data

### PR DESCRIPTION
**Pull request by televator**
Instead of doing the bare HTTP commands yourself, you could use the
ESP32 (and ESP8266) HTTPClient implementation.
The advantages are
- returns a proper error message on failure
- less and more cosise code

However, there are few things I would put up for discussion.
I skipped the line setting the UserAgent, do you want it back?
There are two timeouts you can set of HTTPClient, setTimeout and
setConnectTimeout (see [this
PR](https://github.com/espressif/arduino-esp32/pull/2606)). If you
understood the code correctly, the former is closer to the your original
code (i.e. connection already established, time out on slow server
response), while the latter seems more appropriate imo (i.e. time out on
no connection).
Quick remark, the default timeout for the former is exactly the 5000ms
you had in your code as well.

In my setup the HTTPClient implementation works fine since day one; this
is on an ESP8266, though.

### CODE REVIEW

**Comment by G6EJD** [comment]
There is a problem for the novice user, if they download the files in a ZIP and unpack them to a folder the files epaper_fonts and forecast_record.h and lang.h are not found.

**Comment by televator** [comment]
Can you please give me more details when exactly to problem occurs? I just downloaded the zip, unpacked it and even if I open one of the .ino files in the Arduino IDE it finds all needs. 

Talking about novice users - have you considered making this project part of Arduino library list? This will take some further steps, I guess,... and I am not sure about the license requirements there, but it would definitely boost the user experience.

**Comment by G6EJD** [comment]
If the novice user (in the experience of the emails I get) downloads the zip and then goes to the examples, say v11, the .ino cannot find any of the supporting files such as epaper_font.h

**Comment by televator** [comment]
I think I got this reproduced (in my test before I had the library still in place which made sure that all headers are found). And that is obviously a workflow that does not fit the standardized directory structure that the repo is currently in.

This novice workflow puts up a general question then: "self-contained and self-documented" vs. standardized workflow.
And I think that is something you need to decide as the author and maintainer.

Obviously, I am convinced that the standardized workflow is better for all users and you as the maintainer/author.

**Comment by G6EJD** [comment]
It needs to be a self-contained repo as my ethos is to make things as easy as possible for new users and as I mentioned, my emails indicate getting the software to the (say) desktop is often the hardest thing for them to do, let alone getting the IDE installed. The HTTP Client worked OK. I think it just needs a path in front of the files to direct the compiler to the locations, haven't had time to check myself.

**Comment by televator** [comment]
Just to avoid confusion, when you say "self-contained repo" you talk about self-contained ino files, correct? Just wondering, because the repository will in both cases stay self-contained (excluding the unavoidable external dependencies).
And of course I can only look into the github issue page to see the problems, but not when people write you directly; so I can only make assumptions on questions reaching you.
So you are basically saying more mails have reached you over the last week since the Arduino project structure has been rolled out, is this correct?

If this is the case I am really sorry for the trouble. I am still convinced that "loading the library though the library manager, opening the examples and upload" is as easy as it could get and as such worth aiming for. As an intermediate step downloading/cloning the repo into the libraries folder is imho acceptable.

To be honest I started contributing to this project because I had a hard time getting things to run with the structure it used to be in and I was hoping to make things easier for everyone.

**Comment by G6EJD** [comment]
I get about 20-30 emails a day covering the videos I produce, some days its quite surprising how many I can get. Undoubtedly for me, using the code has to be as simple as possible and I can use it as is it now, but the typical 'workflow' of one of my viewers is to download the zip, find the .ino and compile it, but now that does not work as yes I am receiving emails asking how to go about getting the code to compile and where are the library files?

I am surprised that the Arduino IDE will not find any of the src files unless each is given a specific address so for example:
#include "src/epaper_fonts.h"
does not work, neither does:
#include "../src/epaper_fonts.h" 
or any combination except on my PC:
#include "C:\Users\Admin\ESP32-e-Paper-Weather-Display-master\ESP32-e-Paper-Weather-Display-master\src\epaper_fonts.h"
does, which is clearly not practical, so this seems to be an IDE issue as files should be capable of being included from a subfolder other than the Library folder, but they can't, well not implicitly, explicitly yes.

At the moment I don't know what the answer is.

**Comment by televator** [comment]
The Arduino IDE is really "hacky" when it comes to include paths and library paths. In a nutshell it concatenates and copies all files that *it* considers necessary to a temporary folder and fires up the compiler there. However, the files *it* considers necessary is problematic.
This is also the reason why relative imports won't work and absolute imports do.

If the ino files are loaded from the library it considers the ino files as part of the library and loads (aka. copies) the library as well.
In case of your viewer's workflow it only copies the ino file and the neighboring credentials file to the temporary folder and then the compiler fails to find the other parts.

Maybe you can convince this viewer to look into https://www.arduino.cc/en/Guide/Libraries#toc4
Imho this is really nice graphical support for novice users.

**Comment by G6EJD** [comment]
I'm not disagreeing with you, undoubtedly the way the structure is now is far superior, I just have to find a really easy way to get viewers to use the software, I'll amend the readme and direct them there I think plus your link.
Can we rewind the http merge please.

**Comment by G6EJD** [comment]
After further testing, common.h will not compile with ESP32 core 1.3.1rc1 due to improved compiler checking and it correctly identifies that the revised HTTP section has an ambiguous status on completion, it simply requires an additional 'return true;' after the if tests to resolve this, TRUE is the correct response as any failures will return false.

**Pull request merged**
