### PR TITLE
Waveshare 3.7" Pi Pico and FireBeetle support

### PR DESCRIPTION
**Pull request by grahamwhaley**
Add support for a Waveshare Pi Pico 3.7" display connected
to a DFRobot FireBeetle.

Notable things in this example include:
 - Use u8g2 functions to get string/font sizes rather than
   display.getTextBounds, as it seems more accurate when using
   u8g2 fonts, and makes drawString[MaxWidth] easier to place.
 - Use the calibrated ESP32 adc functions to measure the battery
   voltage, and use a simpler algorithm to predict percentage.
 - For the overnight long sleep period, do a single long sleep
   rather than wake every 30 minutes to check.
 - When the battery voltage is below a dangerous level, print
   a large obvious battery warning on the screen!

Fixes: #181 

Signed-off-by: Graham Whaley <graham.whaley@gmail.com>

### CODE REVIEW

**Comment by G6EJD** [comment]
Thank you

**Comment by grahamwhaley** [comment]
Hi David,
 the PR got closed without a merge - just wanted to check that was the intent?

**Comment by G6EJD** [comment]
I did select Merge, not sure what's gone on here. I did notice the original request remained open though which was confusing. No way to resolve this that I can see.

**Comment by G6EJD** [comment]
I re-opened then merged again, looks OK now.

**Comment by grahamwhaley** [comment]
Yep, that did it - many thanks!

**Pull request merged**
