### PR TITLE
WS_3_7: Fix sleep timer code

### PR DESCRIPTION
**Pull request by grahamwhaley**
It looks like I really messed up the sleep timer code in the original commit when I tried to add the 'overnight long sleep'.

Rewrite that code, to cater for both big sleeps that start either before or after midnight.

Whilst there, make the SleepDuration/WakeupTime/SleepTime variables consts, which specifically in this new code allows the compiler to drop out the case that we are obviously not using. In my local tests this dropped ~100bytes from the image size (and probably saved us a single bit of math/test in the code itself).

Fixes: #217

### CODE REVIEW

**Comment by grahamwhaley** [comment]
It'd be great to get some code review on this, given last time I messed it up!
I've read through the code multiple times, and have it running locally, and I believe it is now doing the right thing...

**Comment by G6EJD** [comment]
Looks OK

**Comment by grahamwhaley** [comment]
Thanks @G6EJD . I think this PR got closed rather than merged - was that the intention? I think that happened on my last PR as well - must be something my PRs throw up that then doesn't do what we expect?

**Comment by G6EJD** [comment]
That’s strange, I merged it then checked the master files were showing updated now but it’s been unwound. Not sure what’s going on!

**Comment by G6EJD** [comment]
I re-opened the pull request and submitted again, it’s showing as successful like last time, but time will tell now.

**Pull request merged**
