### PR TITLE
have german using same obtain_wx_data method

### PR DESCRIPTION
**Pull request by televator**

### CODE REVIEW

**Comment by G6EJD** [comment]
At the moment, I'm not seeing how to use say v11 in German?

**Comment by televator** [comment]
That is true. I already have a branch "german_translations_file" which follows the approach of the others with a lang_de.h, but I haven't checked it properly. Therefore I haven't set up a PR for it, yet.
I tend to drop support for the German file for the time being (maybe also the french non-lang version) and add it again later - what do you think?
This would make a cleanup of the repo much simpler.

**Comment by G6EJD** [comment]
See here form v10a / V11 german: https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/issues/26

**Comment by televator** [comment]
Ah, thanks. Didn't see the conversation. His lang_gr file seems pretty identical to my lang_de file :-D So, can we delete the German directory then? What about the French directory?

**Comment by televator** [comment]
https://github.com/G6EJD/ESP32-e-Paper-Weather-Display/pull/41

**Comment by G6EJD** [comment]
The French is done. The 4.2" needs converting to GxEPD, I might try to do that in the coming days.

**Pull request merged**
