### PR TITLE
Use one forecast_record type

### PR DESCRIPTION
**Pull request by televator**

### CODE REVIEW

**Comment by G6EJD** [comment]
I'm sort of OK with this change, but I don't foresee the record type ever changing. What's your thinking other than reducing the main section code view.

**Comment by televator** [comment]
Sorry for my brevity, I should have explained what I am aiming for.
My long-term goal is that all common code goes into the "library" part i.e. the src/ directory and only the display-size-specific parts are in the examples folders. My hope is not only to reduce the amount of code to maintain/to document, it also helps to make all displays profit from your changes/bugfixes/discoveries.
As an example: Your latest changes towards GxEPD2 are only for the 7.5" module which I don't (yet) have at hand.
I also hope for more flexibility in using a clear separation between lib and module-specific code, to allow many more use-cases.

Of course this change is small and is only to be seen as a tiny first step in this direction.
My main motivation to for these small changes is to get early feedback from your side. It also helps to make reviewing changes easier and reduces the chance of merge problems with changes you currently have in mind.

Another topic I am aiming for is automated testing (in this case only "compiling").
That is why I set up a travis CI job to run on all commits, see
https://travis-ci.org/televator/ESP32-e-Paper-Weather-Display
which currently runs on my PlatformIO branch.

**Comment by G6EJD** [comment]
Ok, understand now. BTW using GxEPD2 and non-pages mode as in v10.0a saves about 3-secs in overall update time which because on time is significant for power consumption is a huge improvement and will further stretch out battery life. Definitely time to move all the codes over to GxEPD2.

**Comment by televator** [comment]
I saw you already tried paged update as well. Do you know about the memory demand for the 4.2"?

**Comment by G6EJD** [comment]
The library authors explains how to work it out, about 400/8*300=15K There is an option to use a half-size buffer too, so even less of a memory demand.
You'd need to use (I think) the functions I produced at the end of the 7.5" version unless you really want to do a lot of conversion work.

**Comment by televator** [comment]
Thanks. Good to know. there might be chance to put in on an esp8266 then.

**Comment by G6EJD** [comment]
4.2” definitely, I tried with the 7.5” but there is just not enough resource to operate, I tried IRAM and moving as much to flash as I could, but no luck and that’s with JSON streaming. It’s possible to split the forecast section into 2 chunks rather than one sequence but I haven’t found the time to do that.

**Pull request merged**
