### PR TITLE
Use common code for decoding weather

### PR DESCRIPTION
**Pull request by televator**
As announced last time this is a first step towards a common code base
for all displays.
Of course this is far from being a nice seperation and modularization,
but it already helps to reduce the amount of lines drastically.

### CODE REVIEW

**Comment by G6EJD** [comment]
Has this been tested?

**Comment by televator** [comment]
Yes and no, unfortunately.
As mentioned before I have automated testing for all example files in my platformio branch - testing with platformio is really easy to set up and works like a charm. There I saw everything is still working as expected. 
But to have my changes based on the master branch I have to trust my git skills and my vague understanding on the magic what the Arduino IDE does when it comes to includes and linking. To be "sure", I tried to compile one example with the Arduino IDE and it worked.

**Comment by G6EJD** [comment]
I've just tried the 7.5" version, that compiles OK.

I think this has gone as far as it needs to now, because my ethos is to help the beginner and it can get too complicated for some who have no experience, I receive a lot, and I mean a lot of emails, asking why the (any) code is not working and this nearly always because they don't know how to download the files or copied only the main .ino and no the rest - confusion then entails. 

So as engineers, we have to get the right balance between code elegance and practicality. 

Thanks for your help in organising all this, it is much appreciated.

**Comment by televator** [comment]
Good to hear that it works for you.
But we are completely on the same page when it comes to usability - I am working exactly in this direction, but maybe I should have provided some more information.

Did you see that cloning your repository into your Arduino libraries folder is enough to get started? No manual copying of single files - just clone it and choose "file" ->"examples" in the Arduino IDE and you're done.
That is why I chose to change the repo structure to comply with the Arduino standard.

IMHO this is really easy and complies with the standard Arduino workflow - I guess this will trigger less questions to you. What do you think?

**Pull request merged**
